config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  resources :microposts

  namespace :api, format: 'json' do
    resources :task_api, only: [:index, :create, :update]
  end

  resources :prefectures, only: [:index] do
    collection do
      get 'edit_ajax'
      post 'update_ajax'
      post 'delete_ajax'
      get 'load_index'
      get 'lists'
      get 'edit_vue'
      get 'load_user'
      get 'load_area'
      post 'add_prefecture'
      post 'change_area_cd'
    end
  end

  resources :trips, only: [:index] do
    collection do
      get 'load_index'
      patch 'update/:id', to: 'trips#update'
      post 'delete'
    end
  end

  resources :tasks, only: [:index] do
    collection do
      get 'hoge'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  # belongs_to :user
  validates :content, length: { maximum: 140 }, presence: true
  validates :user_id, presence: true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  AREAS = [
    { name: '北海道地方', code: '01' },
    { name: '北東北地方', code: '02' },
    { name: '南東北地方', code: '03' },
    { name: '北関東地方', code: '04' },
    { name: '南関東地方', code: '05' },
    { name: '北陸地方', code: '06' },
    { name: '甲信越地方', code: '07' },
    { name: '北近畿地方', code: '08' },
    { name: '南近畿地方', code: '09' },
    { name: '東中国地方', code: '10' },
    { name: '西中国地方', code: '11' },
    { name: '四国地方', code: '12' },
    { name: '北九州地方', code: '13' },
    { name: '南九州地方', code: '14' }
  ].freeze

end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_create :generate_uniq_code
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  def generate_uniq_code
    while (!self.code || User.exists?(code: self.code)) do
      self.code = SecureRandom.hex(15)
    end
  end
end

app/controllers/api/task_api_controller.rb
class Api::TaskApiController < ApplicationController

  # GET /tasks
  def index
    # 後々のため、更新順で返します
    @tasks = Task.order('updated_at DESC')
    render json: @tasks
  end

  # POST /tasks
  def create
    p 'access'

    @task = Task.new(task_params)
p @task.valid?
    if @task.save
      render json: @task, status: :created
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      render :show, status: :ok
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task_api).fetch(:task, {}).permit(:name, :is_done)
    # params.fetch(:task_api, {}).permit(
    #     :name, :is_done
    # )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController

  def index
    @prefectures = Prefecture.all.order(:code)
  end

  def edit_ajax
    @goto_pref, @no_need_pref =  Prefecture.all.partition{|p| p.go_flag}
    render 'edit_ajax', layout: false
  end

  def update_ajax
    @p = Prefecture.find_by(code: setup_update_params)
    @p.update(go_flag: true)
    render partial: 'prefectures_list', locals: {pref: @p}
  end

  def delete_ajax
    @p = Prefecture.find_by(code: params[:code])
    @p.update(go_flag: false)
    render partial: 'prefectures_list', locals: {pref: @p}
  end

  # trip#indexで使用
  def load_index
    @prefectures = Prefecture.all.order(:code)
    render json: @prefectures
  end

  def load_user
    render json: { code: '08', current_company_code: '3' }
  end

  def load_area
    render json: Prefecture::AREAS
  end

  def add_prefecture
    pref = Prefecture.new(add_prefecture_params)
    p add_prefecture_params
    pref.go_flag = false
    pref.save!
    render json: pref
  end

  def change_area_cd
    params.inspect
    pref = Prefecture.find_by(code: params[:prefecture][:code])
    pref.attributes = change_area_cd_params
    pref.save
    render json: pref
  end

  def lists
    a = Prefecture.all.collect{|p| { name: p.name } }
    p a
    render json: a
  end

  def edit_vue
    @prefecture = Prefecture.first
    render json: @prefecture
  end

  private

  def setup_update_params
    params.require(:code)
  end

  def add_prefecture_params
    params.require(:prefecture).permit(:name, :code)
  end

  def change_area_cd_params
    params.require(:prefecture).permit(:code, :area_cd)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index

  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index

  end

  def load_index
    @trips = Trip.all.order(:start_date)
    render json: @trips
  end

  def create

  end

  def update
    trip = Trip.find_by(id: params[:id])
    hoge = params[:trip][:visit_prefectures]
    if hoge
      trip.update(visit_prefectures: hoge)
    else

      trip.update(api_params)
    end
    p trip
    render json: trip
  end

  private

  def api_params
    params.require(:trip).permit(:name, :main_prefecture, :visit_prefectures)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/prefectures/_prefectures_list.html.erb
<% url =  pref.go_flag ? 'delete_ajax' : 'update_ajax' %>

<div class="row">
<div class="col-md-3 hhh"><%= pref.code %></div>
<div class="col-md-3"><%= pref.name %></div>
<div class="col-md-3"><%= pref.go_flag %></div>
<div class="col-md-3"><button class="btn btn-warning <%= pref.go_flag ? 'delete' : 'add' %>" id="<%= pref.code %>">btn</button></div>
</div>

app/views/prefectures/edit_ajax.html.erb
<tr>
  <td colspan="4">
    <div><button class="btn btn-danger close-window">close-x</button></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h3>右へ移動</h3>
      <div class="unlist">
        <% @no_need_pref.each do |ga| %>
        <%= render partial: 'prefectures_list', locals: { pref: ga } %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <h3>左へ移動</h3>
      <div class="list">
        <% @goto_pref.each do |ge| %>
          <%= render partial: 'prefectures_list', locals: { pref: ge }  %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  </td>
</tr>

<script type="text/javascript">
    $('.close-window').on('click', function(){
        $('.close-window').closest('tr').remove();
    })

    $('.unlist').on('click', '.add', function() {
        var $addBtn = $(this);
        post_data($addBtn,'update_ajax','.list');

    });
    $('.list').on('click', '.delete',function() {
        var $delBtn = $(this);
        post_data($delBtn,'delete_ajax','.unlist');

    });
     function post_data(clickObj,action,list){
         var code = clickObj.attr('id');
         // var token = clickObj.closest('.row').find('input[name=authenticity_token]').val();
         // -> jquery-ujs で対応
         var data = {code: code}
        $.ajax({
            url: "prefectures/" + action,
            type: "post",// post delete で分ける
            data: data,
            // body: JSON.stringify(data),
            // contentType: 'json',
            dataType: "html",
            success: function(response_data) {
                clickObj.closest('.row').remove();
                $(list).append(response_data)
            },
            error: function(response_data) {
                // html() と　renderpartial FIleで対応する
                console.log("errror");
            }
        });
    }
    </script>

app/views/prefectures/index.html.erb
<% provide(:title, 'prefecture') %>

<div id="app">
  <prefecture_table></prefecture_table>
</div>

<%= javascript_pack_tag 'prefectures' %>

app/views/static_pages/about.html.erb
<% provide(:title, "Home") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Home") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),'http://rubyonrails.org/' %>

<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'hello_vue' %>

app/views/tasks/index.html.erb
<div id="app">
  <navbar></navbar>
</div>


<div id="todoList">
  <hoge></hoge>
</div>

<%= javascript_pack_tag 'tasks' %>

app/views/trips/index.html.erb
<!--ここは検索画面のコンテンツをつっこむ-->

<!--ここはてーぶるリスト-->

<div id="tripList">
  <trip_table></trip_table>
</div>

<%= javascript_pack_tag 'trips' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>