config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  resources :microposts

  namespace :api, format: 'json' do
    resources :task_api, only: [:index, :create, :update]
  end

  resources :prefectures, only: [:index] do
    collection do
      get 'edit_ajax'
      post 'update_ajax'
      post 'delete_ajax'
      get 'load_index'
      get 'lists'
      get 'edit_vue'
      get 'load_user'
      get 'load_area'
      post 'add_prefecture'
      post 'change_area_cd'
    end
  end

  resources :trips, only: [:index] do
    collection do
      get 'load_index'
      patch 'update/:id', to: 'trips#update'
      post 'delete'
    end
  end

  resources :tasks, only: [:index] do
    collection do
      get 'hoge'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  # belongs_to :user
  validates :content, length: { maximum: 140 }, presence: true
  validates :user_id, presence: true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  AREAS = [
    { name: '北海道地方', code: '01' },
    { name: '北東北地方', code: '02' },
    { name: '南東北地方', code: '03' },
    { name: '北関東地方', code: '04' },
    { name: '南関東地方', code: '05' },
    { name: '北陸地方', code: '06' },
    { name: '甲信越地方', code: '07' },
    { name: '北近畿地方', code: '08' },
    { name: '南近畿地方', code: '09' },
    { name: '東中国地方', code: '10' },
    { name: '西中国地方', code: '11' },
    { name: '四国地方', code: '12' },
    { name: '北九州地方', code: '13' },
    { name: '南九州地方', code: '14' }
  ].freeze

end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_create :generate_uniq_code
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  def generate_uniq_code
    while (!self.code || User.exists?(code: self.code)) do
      self.code = SecureRandom.hex(15)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController

  def index
    @prefectures = Prefecture.all.order(:code)
  end

  def edit_ajax
    @goto_pref, @no_need_pref =  Prefecture.all.partition{|p| p.go_flag}
    render 'edit_ajax', layout: false
  end

  def update_ajax
    @p = Prefecture.find_by(code: setup_update_params)
    @p.update(go_flag: true)
    render partial: 'prefectures_list', locals: {pref: @p}
  end

  def delete_ajax
    @p = Prefecture.find_by(code: params[:code])
    @p.update(go_flag: false)
    render partial: 'prefectures_list', locals: {pref: @p}
  end

  # trip#indexで使用
  def load_index
    @prefectures = Prefecture.all.order(:code)
    render json: @prefectures
  end

  def load_user
    render json: { code: '08', current_company_code: '3' }
  end

  def load_area
    render json: Prefecture::AREAS
  end

  def add_prefecture
    pref = Prefecture.new(add_prefecture_params)
    p add_prefecture_params
    pref.go_flag = false
    pref.save!
    render json: pref
  end

  def change_area_cd
    params.inspect
    pref = Prefecture.find_by(code: params[:prefecture][:code])
    pref.attributes = change_area_cd_params
    pref.save
    render json: pref
  end

  def lists
    a = Prefecture.all.collect{|p| { name: p.name } }
    p a
    render json: a
  end

  def edit_vue
    @prefecture = Prefecture.first
    render json: @prefecture
  end

  private

  def setup_update_params
    params.require(:code)
  end

  def add_prefecture_params
    params.require(:prefecture).permit(:name, :code)
  end

  def change_area_cd_params
    params.require(:prefecture).permit(:code, :area_cd)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end

  def contact
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index

  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index

  end

  def load_index
    @trips = Trip.all.order(:start_date)
    render json: @trips
  end

  def create

  end

  def update
    trip = Trip.find_by(id: params[:id])
    hoge = params[:trip][:visit_prefectures]
    if hoge
      trip.update(visit_prefectures: hoge)
    else

      trip.update(api_params)
    end
    p trip
    render json: trip
  end

  private

  def api_params
    params.require(:trip).permit(:name, :main_prefecture, :visit_prefectures)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg bg-success navbar-dark fixed-bottom footerbar">
    <ul class="navbar-nav mr-auto">
      <a class="navbar-brand" href="/trips">
        <%= image_tag('menu-icons/japan.png', :size => "32x28") %>
      </a>
      <a class="navbar-brand" href="#">
        <%= image_tag('menu-icons/eat.png', :size => "32x28") %>
      </a>
      <a class="navbar-brand" href="/prefectures">
        <%= image_tag('menu-icons/yu.png', :size => "32x28") %>
      </a>
      <a class="navbar-brand" href="#">ー</a>
      <a class="navbar-brand" href="#">を</a>
      <a class="navbar-brand" href="#">せ</a>
      <a class="navbar-brand" href="#">っ</a>
      <a class="navbar-brand" href="#">と</a>
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> menu</a>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success sticky-top">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <a class="navbar-brand" href="#">たびかぜ</a>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn btn-outline-secondary navbar-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag('menu-icons/config.png', :size => "22x22") %>
        </a>
        <div class="dropdown-menu right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= root_path %>">
            <%= image_tag('menu-icons/home.png', :size => "22x22") %>
            HOME
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= help_path %>">
            <%= image_tag('menu-icons/questions.png', :size => "22x22") %>
            HELP
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= signup_path %>">
            <%= image_tag('menu-icons/user.png', :size => "22x22") %>
            LOGIN
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_message.erb
<div id="message">
  <% [:notify, :warning, :error].each do |message_tag| %>
    <% if messages = flash[message_tag] %>
      <% if messages.instance_of?(Array) %>
        <div class='<%= message_tag.to_s %> js-click-hide-self' data-messages='["<%= messages.join('","') %>"]'>
        </div>
      <% elsif messages.instance_of?(String) %>
        <div class="<%= message_tag.to_s %>  js-click-hide-self <%= message_tag.to_s == 'notify' ? 'js-timeout-hide-self' : '' %>" data-messages='["<%= messages %>"]'>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | tabikaze.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render :partial => "layouts/message" %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>